export const business = {
    id: null,
    businessno: null,
    title_name: null,
    business_name: null,
    taxno: null,
    citizen_id: null,
    shipping_address: null,
    shipping_zipcode: null,
    contact_person: null,
    address: null,
    zipcode: null,
    contact_department: null,
    tel_phone: null,
    tel_mobile: null,
    fax: null,
    email: null,
    active_status: null,
    create_date: null,
    update_date: null,
    create_by: null,
    update_by: null,
}