export const cardatabase = {
    id: null,
    carno: null,
    cusno: null,
    businessno: null,
    province: null,
    brand: null,
    car_type: null,
    car_model: null,
    car_cc: null,
    front_tire: null,
    back_tire: null,
    color: null,
    avg_daydistance: null,
    modelcode: null,
    car_speed: null,
    car_chassisno: null,
    car_loading: null,
    car_engineno: null,
    remark: null,
    business_car: null,
}