export const customermodel = {
    id: null,
    cuscode: null,
    title_name: null,
    firstname: null,
    lastname: null,
    citizen_id: null,
    membercode: null,
    member_date: null,
    dateofbirth: null,
    address: null,
    zipcode: null,
    cus_type: null,
    tel: null,
    email: null,
    active_status: null,
    create_date: null,
    update_date: null,
    create_by: null,
    update_by: null,
}