export const supplier = {
    supcode: null,
    supname: null,
    idno: null,
    road: null,
    subdistrict: null,
    district: null,
    province: null,
    zipcode: null,
    tel: null,
    fax: null,
    taxnumber: null,
    email: null,
    active_status: null,
    created_date: null,
    updated_date: null,
    created_by: null,
    updated_by: null,
}